apiVersion: v1
kind: Pod
metadata:
  name: empty-vol-pod
spec:
  volumes:
    - name: html
      emptyDir: {}

  containers:
    - name: nginx
      image: nginx
      ports:
        - containerPort: 80
          name: "http-server"
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: html
    - name: html-updater
      image: alpine
      command: ["/bin/sh", "-c"]
      args:
        - while true; do date >> /html/index.html;
          sleep 10; done
      volumeMounts:
        - mountPath: "/html"
          name: html
